### ISSUE TITLE
loderunner 503 errors

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/ngsa#153]
- we just discovered that loderunner is throwing some 503 errors but there are no server errors
- need to investigate and resolve

- verified this is the sidecar causing the errors so issue can be closed once we deploy the app with fluent bit enabled

**Comment by joaquinrz** [comment]
This requires further investigation, but the 503 errors are likely happening due to the pods being restarted when the request load is high. We would first have to run a test and take a look at the logs right before the pod crashes and gracefully handle the exception. In the event that the pod itself can't handle the high number of requests, we will have to explore options for implementing an horizontal pod autoscaler that will increase the number of pods when the load is high and automatically scale the back down when the load is low.
