### ISSUE TITLE
GO: Deploy LodeRunner to aks-secure-baseline infrastructure

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#617]
## Description
- Deploy LodeRunner to cluster
   - Only hit NGSA-memory
- existing work from spike: https://github.com/retaildevcrews/ngsa/blob/main/spikes/aks-secure-baseline/deployments/spike/common/loderunner.yaml

Acceptance criteria:
- changes to loderunner deployment do not affect current preprod environment.
- loderunner is setup to run continuously
- loderunner is configured to target the in cluster endpoint for ngsa-memory
- infrastructure setup documentation is updated with instructions for running loderunner

References #596

**Comment by gortegaMS** [comment]
@alkofahi Jafar, You might need to add the following FQDN "pkg-containers-az.githubusercontent.com" firewall application rule collection in order to get loderunner able to pull the image refer to section **"Add GitHub Packages (ghcr.io) to firewall white list"** from [Ngsa Helm Readme](https://github.com/retaildevcrews/caf-terraform-landingzones-starter/blob/main/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/README.md) for instructions.
