### ISSUE TITLE
Investigate CAF module naming behavior in latest version

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#678]
There is unexpected behavior with the latest updates to the CAF terraform module. It is not adding prefixes to the key vault name. Investigate the issue. It is possible that it is a breaking change with settings. It is also possible that it is a bug in the terraform module. Investigate and propose next steps.

Multiple people have noticed that the key vault is not being renamed like the other resources with these global settings.
https://github.com/retaildevcrews/caf-terraform-landingzones-starter/blob/main/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/global_settings.tfvars

https://github.com/aztfmod/terraform-azurerm-caf
https://registry.terraform.io/modules/aztfmod/caf/azurerm/latest

Acceptance criteria:
- Determine the root cause of the missing key vault name prefix
- Document and propose next steps

refs: https://github.com/retaildevcrews/ngsa/issues/701

**Comment by kev-ms** [comment]
The key vault naming issue is noticed when exceeding max length(3-24 characters) of full vault name. Since default name takes 10 characters, if you have prefix with more than 14 characters, CAF seems to drop prefix for key vault.

```Vault name and Managed HSM pool name must be a 3-24 character string, containing only 0-9, a-z, A-Z, and -.```

Add docs around standard prefix considerations and submit CAF feedback to add clarity to such behaviour.
