### ISSUE TITLE
Investigate if terraform service principal is being used

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#702]
We need to double check if we're actually running the terraform as the terraform service principal instead of the current user. These variables in the generated terraform.tfvars are not used in the azurerm provider here. https://github.com/retaildevcrews/caf-terraform-landingzones-starter/blob/05181f1b864d96f603909af8b877929eaa3ce2c2/enterprise_scale/construction_sets/aks/main.tf#L42-L48

Docs on the azurerm provider. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret

Acceptance criteria:
- Investigate use of terraform service principal
- Create a bug if terraform is not configured to use service principal

Mention: @AAkindele , @kev-ms , @dsturgell , @atxryan 

refs: https://github.com/retaildevcrews/ngsa/issues/701

**Comment by gortegaMS** [comment]
I think we need to define the scope and the meaning of having Terraform configured to use a service principal.

**Comment by gortegaMS** [comment]
We are not currently using SP to run terraform,  besides as part of provisioning script stabilization issues #709, #704 and #705 removed  components such as Key-Vault and SP creation logic, since it was not working correclty.

Instead Azure logged in user must have enough permission to create all Azure resources.

![image](https://user-images.githubusercontent.com/70150605/115267418-c3ad8b80-a0fe-11eb-92f1-94b90bcf8ddb.png)


A new task suggesting an approach for SP implementation was created, Issue #726
