### ISSUE TITLE
terraform.tfvars variable formatting problem with double quotes

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#705]
Sometimes the client secret will contain a double quote, `"`, and mess up the tfvars file

- Is there a way to automate escaping and adding a backslash?
- Can this be resolved by configuring the client secret outside of the autogenerated terraform.tfvars file?
  - related: https://github.com/retaildevcrews/ngsa/issues/704

refs: https://github.com/retaildevcrews/ngsa/issues/708

**Comment by Natasha-Kohli** [comment]
Another case that I ran into 1 or 2 times (fairly rare but worth mentioning) is when the client secret contains the backslash followed by another symbol. For example, I had a client secret generate with the following 2 symbols "\!" and got the error "The symbol is not a valid escape sequence selector." My understanding is it interprets the backslash as the start of an escape sequence rather than as part of the client secret.
Not sure if using an environment variable for the client secret instead of the tfvars would fix things but I thought the issue was worth calling out.

**Comment by gortegaMS** [comment]
Some items to investigate if we decide to use terraform.tfvars file.

We could use escape character, that means every time we get  secret we need to replace ( " ) by ( \" )  before use it.

https://www.terraform.io/docs/language/expressions/strings.html
