### ISSUE TITLE
Ensure new domain is not created each deployment

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#758]
Initial research findings

**Comment by gortegaMS** [comment]
4/30/2021 - random_domain name attribute is set to blank in file "domain.tfvar" however I cannot do any test at this time since we cannot create more App Service Domains,

I created a support ticket to increase the quote, so at lease I can try my approach of setting a fix domain name.
**fourco** subscription
https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview
