### ISSUE TITLE
log webv results

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#92]
Need to decide where to log webv results. Currently, ACI automatically adds to log analytics but webv will also run on the k8s cluster(s).

Prefer to avoid modifying the application if possible. We pulled app insights out in favor of the ACI log analytics.

**Comment by jofultz** [comment]
I think it should just log to standard out and then get pushed to Log Analytics.  Do we need to do anything to make that happen when deployed in AKS?

**Comment by dsturgell** [comment]
https://dzone.com/articles/export-kubernetes-logs-to-azure-log-analytics-with

**Comment by bartr** [comment]
We could use Prometheus + Fluent or a sidecar.

I wasn't able to get Fluent working, so I built a sidecar and have it deployed and working e2e on webv (in the nginx branch)

Since it's working, I recommend we go with that for M1 and do a spike on Prometheus + Fluent (or whatever) once we know the stack.

I fear that Prometheus + Fluent will do the same thing as ACI and cram all the data into RawData which makes querying a lot harder, slower and more expensive. The sidecar uses strongly-typed fields for each value.
