### ISSUE TITLE
Remove App Insights from app

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#93]
From discussion notes:
> since we are using log analytics, we don't need app insights. If the key isn't specified, the logs are disabled, so I recommend we remove the key from setup and leave the code as-is.

- [ ] Remove from setup documentation
- [ ] Remove from any existing setup or workflow

Reference #44

**Comment by jofultz** [comment]
I think this should just log to stdout so that it may be picked up and shipped to the log analytics platform.  For our first pass this is probably Log Analytics, but will likely have a different target when we move to WCNP platform items.

- Do we need any special configuration to get log information shipped from the app running in AKS to log analytics?
- The current Helium app emits only a single App Insights metric.  May we remove that metric?

**Comment by bartr** [comment]
I agree. I think we remove App Insights from the app and send everything to Log Analytics via stdout.

I have a side car built for webv that does this today. I recommend we use the sidecar approach for M1. We can change it once we understand the full stack. It's a much simpler setup than getting Prometheus, et. al setup and working, so I'd rather do that work after we know the full stack so we don't have to redo the work. We could also do the work in parallel.

I also think that Prometheus will do the same thing that ACI does and cram everything into the RawData field. The side car puts the values in distinct, strongly-typed fields which makes querying MUCH easier, faster and cheaper.
